"""empty message

Revision ID: 6edd2d496dbf
Revises: 6f4e628b3d99
Create Date: 2020-08-28 08:29:57.766688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6edd2d496dbf'
down_revision = '6f4e628b3d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idol',
    sa.Column('idol_id', sa.Integer(), nullable=False),
    sa.Column('fans_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idol_id', 'fans_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idol')
    # ### end Alembic commands ###
